### ISSUE TITLE
Cannot set links on TreeNodes

### ISSUE THREAD

**Issue by gigacool** [react-component/tree#63] opened 2017-03-06 10:37 UTC
Hi,

 I met the functional need to provide the treenodes with links to route through the application, I can inject link through title property and it works, however, I start to get tons of warning through the tree because the TreeNode component wraps content in an anchor (nested anchor warning).

`<TreeNode {...node} title={<Link to ={node.url}>{node.title}</Link>}>`

would it be possible to directly inject href on the TreeNode to make use of the anchor. that would improve the behavior and avoid scaring product owner with tons of react warnings. Something like

`<TreeNode {...node} href={node.url}>`

I can see it in there https://github.com/react-component/tree/blob/master/src/TreeNode.jsx#L309 

What do you think ? Thanks for feedbacks

**Comment by yesmeck** [comment] 2017-03-06 11:08
Duplicate of #44. PR is welcome.

**Closed by yesmeck** 2017-03-06 11:08 UTC
